### ISSUE TITLE
Oops an error occured!

### ISSUE THREAD

**Issue by cosmox** [dwenzel/placements#50]
Bei der BGA Seite gibt es wiederkehrende Störungen: 
The ColumnMap for property "type" of class "Webfox\Placements\Domain\Model\Position" is missing.

Das geht erst wieder nach dem löschen sämtlicher Caches, any Idea?

**Comment by dwenzel** [comment]
Der Fehler ist beim Entwicklen auch aufgetreten, aber eigentlich nur, wenn am Model Änderungen vorgenommen wurden. Dann behoben mit Cache löschen. 
Versuch mal, die Extension zu deinstallieren und wieder zu installieren. Das sollte den Extbase-Cache löschen...

Am 30.01.2014 um 10:04 schrieb Michael Kasten:

**Comment by cosmox** [comment]
Das Problem taucht leider täglich auf und lässt sich nur beheben durch "Alle Caches löschen", ist das ein Fehler im Extbase-Cache?

**Comment by dwenzel** [comment]
Sorry Micha, solange ich nicht mehr über den Fehler weiß, hab ich keine Idee, was schief laufen könnte. 
Die einzige Chance, die ich sehe, ist es, die gesamte Instanz mit allen Daten in die Entwicklungsumgebung zu kopieren, dort den Debug-Level zu erhöhen und den Fehler zu provozieren...

**Comment by cosmox** [comment]
Die komplette Dev Installation habe ich bereits abgeglichen, diese Fehler sind leider mittlerweile richtige ärgerlich, das einzige was ich jetzt noch vermute ist keine ausreichende TYP Prüfung, auf der Dev version verhält sich das dann auch entsprechende zwei dreimal kann man die Detailansicht einer Stelle klicken, dann plötzlich steigt alles aus, dabei klick ich z.T. auf die gleichen Stellen die vor wenigen Sekunden noch angezeigt worden sind. Mehr kann ich dazu derzeit auch nicht beitragen

**Comment by dwenzel** [comment]
@cosmox It seems our discussion drifted away from the orginal issue. I assume this issue does not happen anymore
