### ISSUE TITLE
IE9 Kein Suchergebniss ohne Ort

### ISSUE THREAD

**Issue by cosmox** [dwenzel/placements#51]
Unter IE9 wird keine Suchergebnis erzeugt solange man nicht explizit einen Ort mitgibt, damit erzeugen alle Direktverlinkungen auf die Suche eine leere Trefferliste (also die Verlinkungen aus  den einzelnen Berufen auf die Suche)

**Comment by dwenzel** [comment]
This might be due to IE restrictions concerning the number of characters in URLs.

**Comment by dwenzel** [comment]
This error occurs only if a JavaScript placeholder plugin is present. In your case google maps Autocomple for places does not work correctly with an existing placeholder in IE9. When posting the form the placeholder value is posted as _value_ of the formfield and therefore no search result can be found.
Solution: Don't use a placeholder attribute when using google maps Autocomplete for places.
