### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by cosmox** [dwenzel/placements#52]
Das sollte im Controller abgefangen werden:
Division by zero in /home/wf10343/bga/typo3conf/ext/placements/Classes/ViewHelpers/Widget/Controller/PaginateController.php line 93

**Comment by dwenzel** [comment]
We do have a default value of 10 for itemsPerPage (see line 41: property configuration is an array). This is overruled when merging with the given configuration array from the ViewHelper and the ViewHelper only checks for the existence of this variable.

**Comment by dwenzel** [comment]
@cosmox I guess this issue can be closed?

**Comment by cosmox** [comment]
yes please
