### ISSUE TITLE
Unterschiedliche Suchergebnisse

### ISSUE THREAD

**Issue by cosmox** [dwenzel/placements#53]
In einem Account sind 47 Stellen eingestellt, nach dem login und dem aufruf der Seite mit den Stellenangeboten werden 30 davon angezeigt, erst wenn der User auf Suchen klickt werden die restlichen 17 mit ausgeworfen.

**Comment by cosmox** [comment]
In one account 47 digits are set, after the login, and the calling of the page with the vacancies are displayed 30 of them, only when the user clicks on the remaining 17 are displayed with Search.

**Comment by dwenzel** [comment]
@cosmox Can this issue be closed?

**Comment by cosmox** [comment]
i think so
