### ISSUE TITLE
Oops, an error occurred!

### ISSUE THREAD

**Issue by cosmox** [dwenzel/placements#54]
PHP Catchable Fatal Error: Argument 2 passed to TYPO3\CMS\Fluid\ViewHelpers\Link\ActionViewHelper::render() must be of the type array, null given in /usr/local/share/php/typo3/typo3_src-6.1.7/typo3/sysext/fluid/Classes/ViewHelpers/Link/ActionViewHelper.php line 68

But deleting the caches is no solution anymore, any ideas

**Comment by cosmox** [comment]
That was an effect by old  cashehashes?

**Comment by dwenzel** [comment]
Can you track down where the error occurred?
The PHP error messages does not show which template was affected...
